@echo off
mkdir plateforme-xp
cd plateforme-xp
mkdir src
mkdir src\app
mkdir src\app\api
mkdir src\app\api\auth
mkdir src\app\api\xp
mkdir src\app\api\badges
mkdir src\app\api\events
mkdir src\app\api\peers
mkdir src\app\api\resources
mkdir src\app\dashboard
mkdir src\app\profile
mkdir src\app\calendar
mkdir src\app\tutoring
mkdir src\components
mkdir src\components\gamification
mkdir src\components\calendar
mkdir src\components\tutoring
mkdir src\components\layout
mkdir src\lib
mkdir src\models
mkdir src\types
mkdir src\utils
mkdir public
